import { StyleSheet } from 'react-native';

export const getStyles = (currentColors: any) => StyleSheet.create({
    modalOverlay: {
        flex: 1, 
        backgroundColor: 'rgba(0,0,0,0.6)', 
        justifyContent: 'flex-end',
    },
    modalCard: {
        backgroundColor: currentColors.background, 
        paddingHorizontal: 24, 
        paddingTop: 12, 
        paddingBottom: 32, 
        borderTopLeftRadius: 30, 
        borderTopRightRadius: 30,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 10,
    },
    modalHandle: {
        width: 45,
        height: 5,
        backgroundColor: currentColors.border,
        borderRadius: 3,
        marginBottom: 24,
    },
    iconContainer: {
        width: 76,
        height: 76,
        borderRadius: 38,
        backgroundColor: currentColors.primary + '20', 
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontFamily: 'Montserrat-Bold', 
        color: currentColors.text, 
        fontSize: 22, 
        marginBottom: 10, 
        textAlign: 'center',
    },
    modalDesc: {
        fontFamily: 'Inter-Regular', 
        color: currentColors.muted, 
        fontSize: 15, 
        textAlign: 'center', 
        marginBottom: 30, 
        lineHeight: 22, 
    },
    modalButtonPrimary: {
        backgroundColor: currentColors.primary, 
        width: '100%', 
        paddingVertical: 16, 
        borderRadius: 14, 
        alignItems: 'center', 
        marginBottom: 12,
        shadowColor: currentColors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 3,
    },
    modalButtonPrimaryText: {
        fontFamily: 'Inter-Bold', 
        color: '#ffffff',
        fontSize: 16,
    },
    modalButtonSecondary: {
        paddingVertical: 12,
        width: '100%',
        alignItems: 'center',
    },
    modalButtonSecondaryText: {
        fontFamily: 'Inter-Medium', 
        color: currentColors.muted, 
        fontSize: 15,
    },
    imageContainer: {
        width: 120,
        height: 120,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    modalImage: {
        width: '100%',
        height: '100%',
    },
});